management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
spring:
  application:
    name: sping-cloud-client
  cloud:
    config:
      server:
        git:
          uri: ${user.dir}/src/main/resources/configs

server:
  port: 9696
